version: "3.0"
services:
  elk:
    image: sebp/elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
  pg:
      image: postgres
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: candor
        POSTRGES_PASSWORD: candor
        POSTGRES_DB: candor